// apps/client/src/components/animated-number.tsx
import { createEffect, createSignal } from "solid-js"

type Props = {
  value: number
  duration?: number
  compact?: boolean
}

const compactFormatter = new Intl.NumberFormat("en", {
  notation: "compact",
  compactDisplay: "short",
})

const standardFormatter = new Intl.NumberFormat("en-US")

export function AnimatedNumber(props: Props) {
  const [displayValue, setDisplayValue] = createSignal(props.value)
  const [prevValue, setPrevValue] = createSignal(props.value)

  createEffect(() => {
    if (props.value === prevValue()) return

    const start = prevValue()
    const end = props.value
    const duration = props.duration || 300
    const startTime = performance.now()

    const animate = (currentTime: number) => {
      const elapsed = currentTime - startTime
      const progress = Math.min(elapsed / duration, 1)

      // Функция плавности (ease-out)
      const easeProgress = 1 - Math.pow(1 - progress, 3)

      const current = start + (end - start) * easeProgress
      setDisplayValue(Math.round(current))

      if (progress < 1) {
        requestAnimationFrame(animate)
      }
    }

    setPrevValue(props.value)
    requestAnimationFrame(animate)
  })

  return (
    <>{props.compact !== false ? compactFormatter.format(displayValue()) : standardFormatter.format(displayValue())}</>
  )
}

// apps/app/src/components/AnimatedNumber.vue
<template>
  <span>{{ formattedValue }}</span>
</template>

<script setup lang="ts">
import { ref, watchEffect, computed } from 'vue'

interface Props {
  value: number
  duration?: number
  compact?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  duration: 300,
  compact: false,
})

const compactFormatter = new Intl.NumberFormat('en', {
  notation: 'compact',
  compactDisplay: 'short',
})

const standardFormatter = new Intl.NumberFormat('en-US')

const displayValue = ref(props.value)
const prevValue = ref(props.value)

const formattedValue = computed(() => {
  return props.compact
    ? compactFormatter.format(displayValue.value)
    : standardFormatter.format(displayValue.value)
})

watchEffect(() => {
  if (props.value === prevValue.value) return

  const start = prevValue.value
  const end = props.value
  const duration = props.duration
  const startTime = performance.now()

  const animate = (currentTime: number) => {
    const elapsed = currentTime - startTime
    const progress = Math.min(elapsed / duration, 1)

    // Функция плавности (ease-out)
    const easeProgress = 1 - Math.pow(1 - progress, 3)

    const current = start + (end - start) * easeProgress
    displayValue.value = Math.round(current)

    if (progress < 1) {
      requestAnimationFrame(animate)
    }
  }

  prevValue.value = props.value
  requestAnimationFrame(animate)
})
</script>
